### PR TITLE
SchemaDotOrg bugfix: No longer escape the content of "ld+json" during…

### PR DESCRIPTION
**Pull request by apepper**
… prerender.

Otherwise the script content will be sanitize by react, which yields prerendered pages where schema dot org is not working.

Reported by @dpetryk .

### CODE REVIEW

**Comment by dcsaszar** [comment]
Thoughts: I‘d rather leave dangerous options to the developer, instead of enabling it by default.
See https://github.com/json-ld/json-ld.org/issues/390.

What exactly is the reported issue?

**Comment by apepper** [comment]
> What exactly is the reported issue?

How to reproduce:

```
curl https://www.scrivito.com/example-app-updates-75d8282a00406d70 | grep "application/ld+json"
```

Expected:

```html
<script type="application/ld+json">{"@context":"http://schema.org","@type":"BlogPosting","author":{"@context":"http://schema.org","@type":"Person","name":"Antony Siegert","image":"https://cdn0.scrvt.com/scrival/405a824b3cbf3c48/de6676aadd27/v/7efcbea2d740/Antony-headshot.jpeg"},"datePublished":"2019-03-04","description":"What is new in the Example App?\nThe Example App has been a big part of the Scrivito journey, not only for you – our customers – but also for us as developers. We developed the Example App to showcase some of what could be done when implementing a Scrivito-based app. It is used, every day, to test...","headline":"Example App Updates","image":"https://cdn0.scrvt.com/scrival/424a30fd4efbb522/753f5dd04322/v/daa2f2e61a9b/giovanni-randisi-219945.jpg"}</script>
```

Actual:

```html
<script type="application/ld+json">{&quot;@context&quot;:&quot;http://schema.org&quot;,&quot;@type&quot;:&quot;BlogPosting&quot;,&quot;author&quot;:{&quot;@context&quot;:&quot;http://schema.org&quot;,&quot;@type&quot;:&quot;Person&quot;,&quot;name&quot;:&quot;Antony Siegert&quot;,&quot;image&quot;:&quot;https://cdn0.scrvt.com/scrival/405a824b3cbf3c48/de6676aadd27/v/7efcbea2d740/Antony-headshot.jpeg&quot;},&quot;datePublished&quot;:&quot;2019-03-04&quot;,&quot;description&quot;:&quot;What is new in the Example App?\nThe Example App has been a big part of the Scrivito journey, not only for you – our customers – but also for us as developers. We developed the Example App to showcase some of what could be done when implementing a Scrivito-based app. It is used, every day, to test...&quot;,&quot;headline&quot;:&quot;Example App Updates&quot;,&quot;image&quot;:&quot;https://cdn0.scrvt.com/scrival/424a30fd4efbb522/753f5dd04322/v/daa2f2e61a9b/giovanni-randisi-219945.jpg&quot;}</script>
```

Found thru https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.scrivito.com%2Fexample-app-updates-75d8282a00406d70

**Comment by dcsaszar** [comment]
The underlying issue seems to be React too aggressively escaping (namely double quotes in text nodes).
AFAICS https://github.com/facebook/react/pull/14265 would fix the issue. Should we just wait for this to land? WDYT?

**Comment by dcsaszar** [comment]
Looks like the state of React here isn't going to change soon. How about my proposal of

> if we're going the unsafe workaround route, we should add something like https://github.com/Radagaisus/escape-html-in-json to get back to the safe zone.

**Comment by apepper** [comment]
REVIEW (9aeebe8)

* Added html escaping to SchemaDotOrg.

**Pull request merged**
